# Blog info
#blog_name: 正念和我
#blog_name: 正念之我
#blog_name: 正念叨蜜
blog_name: 正念多蜜
#slogan: Code and debug
slogan: Debug and fix
url: http://zhengnian.me

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/favicon.png

# For seo
keywords: 正念和我,正念之我,正念叨蜜,正念多蜜,Android,AOSP,Mobile,Java,Web,后端开发,Javascript,nodejs,Bash,Ubuntu,MySQL,Spring

home_nav:
  - name: 项目
    url: /project/
    target_blank: false
  - name: 博客
    url: /archive
    target_blank: false
  - name: 找我
    url: /about
    target_blank: false

# config page nav
page_nav:
  - name: 项目
    url: /project/
    target_blank: true #在新页面打开
  - name: 博客
    url: /archive/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 找我
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: true # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Find me~

link_slogan:
  isShow: true # true|fase
  text: "交换友链可以邮件到：ander.joe.sun@gmail.com"


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，赏乔风
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
#personal_style: /css/your-styles.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics: ""
baidu_analytics: ""

# Comment service

# disqus_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
# uyan_key:

# 畅言, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  这里开启
  changyan_appid:
  changyan_appkey:

# gitalk评论组件，把下面的配置换成你的，官方文档: https://gitalk.github.io/
# 步骤：先登录github，然后创建一个认证应用：setting -> developer settings -> https://github.com/settings/developers -> https://github.com/settings/applications/new 取个名字，然后Homepage URL和callback URL都添写博客网址（如果你的博客使用了https，例如codings.net强制启用了https，则这二个项都必须https版的首页地址：例如：https://zhengnian.me，如果是http的，则会在url栏中出错：error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application），然后注册成功后会获得Client ID和Client Secret，把它们填下面，而owner和admin都必须是github的用户名。然后要根据下面的“repo”建相应名称的git仓库（如果不做此步，则博客网页相应处会报错：Error: Not Found），选public，然后创建，然后到settings中确认issues复选框已勾选，然后到点击code右边的issues标签来添加一个issue并提交，然后再到博客页面刷新一下就可以看到“未找到相关的issue评论，请联系xxx初始化创建”，这时只需让博主主点下“使用Github登录”来登录下github并点击相应的初始化按钮后就可以看到正常的评论界面了。这时其它用户可以评论了。最后要在layout/_partial/component/gitalk.ejs中截短下title以使得评论功能不受字数限制而正常使用（本主题默认已作处理，具体见gitalk.ejs）。
gitalk:
  enable: true # 如果使用 gitalk，请设置改之为true
  clientID: 318e6e0a541b38638345
  clientSecret: 1f3ebda3ca2d983027f2188d3334b0a3a7001853
  repo: blog-comment
  owner: AnderJoeSun
  admin: AnderJoeSun


# gitment comment service
gitment:
  enable: false  # true | false  这里开启
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "追求极致效率的Android程序员"
    - "Java/Android/AOSP/C/C++/Linux/JEE/JS/Python/Bash"
    - "正在找新工作，期待能在大平台沉淀以稳定发展，欢迎HR大大们来撩~"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "AnderJoeSun"
    text_value_url: https://github.com/AnderJoeSun
  - type: mail
    icon: icon-mail
    text_key: "Gmail"
    text_value: "ander.joe.sun@gmail.com"
    text_value_url: "mailto:ander.joe.sun@gmail.com"
  - type: location
    icon: icon-location
    text_value: 深圳

link:
  - name: Forsigner
    info: 前端工程师
    url: http://forsigner.com/
    avatar: http://forsigner.com/images/avatar.jpg


project:
  - type: personal
    name: AndroidDialer
    url: http://zhengnian.me/2020/01/22/android.phone.app/
    intro: "一个为长辈打造的、极简的、开源的Android电话应用，能与系统自带的电话应用并存，并可被设置为默认电话应用以替代系统自带的电话应用。"
  - type: personal
    name: MySettings
    url: http://zhengnian.me/2013/06/20/bug023.a20.aosp4.2/
    intro: "一个系统设置应用，方便Android系统开发者获得一些特殊的信息，例如：自动抽取桌面Launcher的布局并保存到一个xml文件中；获取最近运行应用的包名与类名信息等等。"
  - type: personal
    name: JoyuChat
    url: https://github.com/AnderJoeSun/JoyuChat
    intro: "一款用Java开发的类似QQ的聊天软件。11年前的本科毕业设计作品，虽然代码现在看起来很丑，但当时的每一行都因她而很用心:) "  
